name: Swift Dependencies
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    container: swift:6.2
    steps:
      - name: â¬‡ï¸ Checkout Code
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1

      - name: â„¹ï¸ Show Swift Version
        run: swift --version

      - name: ğŸ”„ Restore `.build` Folder
        run: swift package resolve

      - name: ğŸ“¦ Update Dependencies
        run: swift package update hummingbird

